name: practice_job_app_fl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  http: ^1.3.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.0
  get: ^4.6.5
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.0.4+1
  flutter_chat_bubble: ^2.0.2
  flutter_animate: ^4.1.1+1
  image_cropper: ^8.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
